spring:
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijk
      expire: 7
  mail:
    host: smtp.163.com
    username: Jade0v0@163.com
    password: HUfnrH6Pxiu8j4zk
    properties:
      from: Jade0v0@163.com
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
  datasource:
    username: remoteUser
    password: 20041114Liuyu!
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.137.146.104/study_project_demo2
